# Generated by generate-wrapper-unit-tests.py; do not edit.
set(P101_FAULT_SHARD_TESTS
    test_fault_wrappers_complex
    test_fault_wrappers_fenv
    test_fault_wrappers_inttypes
    test_fault_wrappers_locale
    test_fault_wrappers_math
    test_fault_wrappers_signal
    test_fault_wrappers_stdio
    test_fault_wrappers_stdlib
    test_fault_wrappers_string
    test_fault_wrappers_time
    test_fault_wrappers_wchar
    test_fault_wrappers_wctype
)
